pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-webhook
    tag: [ "latest" ]
    when:
      branch: master
      event: push

plugin:
  name: Webhook
  desc: Send build status notifications via Webhook
  type: notify
  image: plugins/drone-webhook
  labels:
    - notify
    - webhook
    - rest
    - json
    - hook
